Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/02/2023
Var
// Seção de Declarações das variáveis 
n1: inteiro
n2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("digite um numero")
leia(n1)

escreval("digite um numero")
leia(n2)

ENQUANTO n1 <> 0 FACA
n1:= n1+n2
escreval("total: ", n1)

FIMENQUANTO

Fimalgoritmo